
package netbanking;

import com.raven.connection.DatabaseConnection;
import com.raven.model.ModelUser;
import com.raven.service.ServiceUser;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author aishh
 */
public class Deposit extends javax.swing.JFrame {

    /**
     * Creates new form Deposit
     */
    private ModelUser currentUser;
     private ServiceUser service;
     private Connection con;
     
    public Deposit(ModelUser user, Connection con, ServiceUser service) {
        initComponents();
       this.currentUser = user;
        this.con = con;
        this.service = service;
         BigDecimal Balance = currentUser.getBalance();
          int accountNumber = currentUser.getAccountNumber();
    }
    public ModelUser getCurrentUser()
    {
        return currentUser;
    }
   public Deposit(){
       
   }
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jpanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        amt_dep = new javax.swing.JTextField();
        accno = new javax.swing.JTextField();
        deposit1 = new javax.swing.JButton();
        depositreset = new javax.swing.JButton();
        depositback = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Jpanel1.setBackground(new java.awt.Color(39, 144, 191));
        Jpanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 255)));
        Jpanel1.setPreferredSize(new java.awt.Dimension(933, 537));
        Jpanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Myanmar Text", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username");
        Jpanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 171, -1, -1));

        jLabel2.setFont(new java.awt.Font("Myanmar Text", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Account Number");
        Jpanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, -1));

        jLabel4.setFont(new java.awt.Font("Myanmar Text", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Amount to Deposit");
        Jpanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 309, -1, -1));
        Jpanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 166, 427, 30));

        amt_dep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                amt_depKeyPressed(evt);
            }
        });
        Jpanel1.add(amt_dep, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 304, 427, 30));

        accno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                accnoKeyPressed(evt);
            }
        });
        Jpanel1.add(accno, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 230, 427, 30));

        deposit1.setBackground(new java.awt.Color(167, 216, 255));
        deposit1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        deposit1.setText("Deposit");
        deposit1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(31, 73, 146), 3));
        deposit1.setPreferredSize(new java.awt.Dimension(100, 45));
        deposit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deposit1ActionPerformed(evt);
            }
        });
        Jpanel1.add(deposit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, -1, -1));

        depositreset.setBackground(new java.awt.Color(167, 216, 255));
        depositreset.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        depositreset.setText("Reset");
        depositreset.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(31, 73, 146), 3));
        depositreset.setPreferredSize(new java.awt.Dimension(100, 45));
        depositreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositresetActionPerformed(evt);
            }
        });
        Jpanel1.add(depositreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, -1, -1));

        depositback.setBackground(new java.awt.Color(167, 216, 255));
        depositback.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        depositback.setText("Back");
        depositback.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(31, 73, 146), 3));
        depositback.setPreferredSize(new java.awt.Dimension(100, 45));
        depositback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositbackActionPerformed(evt);
            }
        });
        Jpanel1.add(depositback, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 420, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Deposit ");
        Jpanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 62, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Jpanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 933, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Jpanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void depositresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositresetActionPerformed
        username.setText(null);
        amt_dep.setText(null);
        accno.setText(null);
 
    }//GEN-LAST:event_depositresetActionPerformed

    private void depositbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositbackActionPerformed
        
        Menu1 depo=new Menu1(currentUser,con,service);
        depo.setVisible(true);
        this.toBack();
        dispose();
    }//GEN-LAST:event_depositbackActionPerformed

    private void accnoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_accnoKeyPressed
        // no string or special characters can be entered
        char c = evt.getKeyChar();
        if(!Character.isDigit(c) && !Character.isWhitespace(c) && !Character.isISOControl(c)) {
            accno.setEditable(false);
            JOptionPane.showMessageDialog(null, "Alphabets and Special characters are not allowed.");
            accno.setEditable(true);
        }
    }//GEN-LAST:event_accnoKeyPressed

    private void amt_depKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amt_depKeyPressed
        // no string or special characters can be entered
        char c = evt.getKeyChar();
        if(!Character.isDigit(c) && !Character.isWhitespace(c) && !Character.isISOControl(c)) {
            accno.setEditable(false);
            JOptionPane.showMessageDialog(null, "Alphabets and Special characters are not allowed.");
            accno.setEditable(true);
        }
    }//GEN-LAST:event_amt_depKeyPressed

    private void deposit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deposit1ActionPerformed
        if(username.getText().length()<=0 || amt_dep.getText().length()<=0 || accno.getText().length()<=0)
        {
            JOptionPane.showMessageDialog(null,"Textboxs not filled");
        }
        else{
        username.setText(null);
        
        String amtDepText = amt_dep.getText();
        accno.setText(null);
        
//        double amount = Double.parseDouble(amt_dep.getText());
        try {
            ModelUser user = getCurrentUser();
            double amount = Double.parseDouble(amt_dep.getText());
            service.deposit(user, amount);
            JOptionPane.showMessageDialog(null, String.format("$%.2f deposited successfully", amount));
        } catch (SQLException e) {
           JOptionPane.showMessageDialog(this, "Feild Error");
        }
            
        }
    }//GEN-LAST:event_deposit1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
 try {
            DatabaseConnection.getInstance().connectToDatabase();
            System.out.println("Connection Succesfully to main page");
        } catch (SQLException e) {
 
            e.printStackTrace();
            System.out.println("Connection not Succesfully to main page");
        }
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Deposit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Jpanel1;
    private javax.swing.JTextField accno;
    private javax.swing.JTextField amt_dep;
    private javax.swing.JButton deposit1;
    private javax.swing.JButton depositback;
    private javax.swing.JButton depositreset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
